name: "🐛 Bug Report"
description: Create a report to help us improve.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Before submitting!
        Please check if this bug has already been reported in the "Issues" tab.

  - type: checkboxes
    id: duplicate_check
    attributes:
      label: Duplicate check
      options:
        - label: I have searched for existing issues and didn't find any.
          required: true

  - type: dropdown
    id: launcher
    attributes:
      label: Launcher
      description: Which launcher are you using?
      options:
        - Prism Launcher
        - CurseForge App
        - Official Launcher
        - ATLauncher
        - Other
    validations:
      required: true
      
  - type: input
    id: video_link
    attributes:
      label: Video / Screenshot Link
      description: Provide a link to a video or screenshot (YouTube, Streamable, Imgur, etc.) showing the bug.
      placeholder: https://youtu.be/...
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log file / Crash Report
      description: Paste the content of your latest.log or crash-report here. Please use code blocks.
      render: java
    validations:
      required: false
