name: "💡 Feature Request"
description: Suggest a new idea for the mod.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: pitch
    attributes:
      label: Idea Description
      description: What would you like to see added?
      placeholder: I think Hamis should be able to wear hats...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Why?
      description: How does this improve the gameplay?
    validations:
      required: false